### ISSUE TITLE
Margin issue in GNOME 3.35.91

### ISSUE THREAD

**Issue by raghav18gupta** [biji/simplenetspeed#16]
![image](https://user-images.githubusercontent.com/12626208/76314775-6e992680-62fd-11ea-8703-66cbcd4e32c1.png)

**Comment by HazilMohamed** [comment]
I got the same error too, I tweaked some of CSS to make it to the center. I opened a pull request #17, now it is placed center for me,

**Comment by reuixiy** [comment]
Encountered the same issue, just edit

`~/.local/share/gnome-shell/extensions/simplenetspeed@biji.extension/stylesheet.css`

For me, I just emptied the file and added:

```css
.simplenetspeed-label,
.simplenetspeed-label-w {
    margin-top: 4px;
}
```
